---
# tasks file for initialization
- name: Downloading GoCD server on Linux
  get_url:
    url: https://download.gocd.org/gocd.repo -o /etc/yum.repos.d/gocd.repo
    dest: /etc/yum.repos.d/gocd.repo


- name: Installing GoCD server on Linux
  yum:
    name: go-server
    state: latest 