---
# tasks file for installation
- name:  Download the latest nexus.
  get_url:
    url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /app
- name: extract
  unarchive:
    src: /app/nexus-3.22.0-02-unix.tar.gz
    dest: /app

- name: Create a tar.gz archive of a single file.
  unarchive:
    src: /app/nexus-3.22.0-02-unix.tar.gz
    dest: /app/
    remote_src: True
- name: Synchronization of src on the control machine to dest on the remote hosts
  copy:
    src: /app/nexus-3.22.0-02/
    dest: /app/nexus
    remote_src: True
    directory_mode: raw
- name: create user
  user:
    name: nexus
- name: Change file ownership, group and permissions
  file:
    path: /app/nexus/
    path: /app/sonatype-work
    owner: nexus
    group: nexus
    directory_mode: raw
    recurse: yes
- name: Set run_as_user="nexus"
  lineinfile:
    path: /app/nexus/bin/nexus.rc
    regexp: '^run_as_user '
    insertafter: '^#run_as_user '
    line: run_as_user="nexus"
- name: Copy the nexus.service file
  copy:
    src: /home/salama/ITI/Ansible/Nexus/nexus.service
    dest: /etc/systemd/system/

- name: Check Config
  command: chkconfig nexus on
- name: Start Nexus
  service:
    name: nexus
    state: started